<?php
/**
 * @brief		latestMoodUpdates Widget
 * @author		<a href='http://www.invisionpower.com'>Invision Power Services, Inc.</a>
 * @copyright	(c) 2001 - SVN_YYYY Invision Power Services, Inc.
 * @license		http://www.invisionpower.com/legal/standards/
 * @package		IPS Social Suite
 * @subpackage	bdmoods
 * @since		22 Dec 2015
 * @version		SVN_VERSION_NUMBER
 */

namespace IPS\bdmoods\widgets;

/* To prevent PHP errors (extending class does not exist) revealing path */
if ( !defined( '\IPS\SUITE_UNIQUE_KEY' ) )
{
	header( ( isset( $_SERVER['SERVER_PROTOCOL'] ) ? $_SERVER['SERVER_PROTOCOL'] : 'HTTP/1.0' ) . ' 403 Forbidden' );
	exit;
}

/**
 * latestMoodUpdates Widget
 */
class _latestMoodUpdates extends \IPS\Widget
{
	/**
	 * @brief	Widget Key
	 */
	public $key = 'latestMoodUpdates';
	
	/**
	 * @brief	App
	 */
	public $app = 'bdmoods';
		
	/**
	 * @brief	Plugin
	 */
	public $plugin = '';
	
	/**
	 * Initialise this widget
	 *
	 * @return void
	 */ 
	public function init()
	{
		// Use this to perform any set up and to assign a template that is not in the following format:
		// $this->template( array( \IPS\Theme::i()->getTemplate( 'widgets', $this->app, 'front' ), $this->key ) );
		// If you are creating a plugin, uncomment this line:
		// $this->template( array( \IPS\Theme::i()->getTemplate( 'plugins', 'core', 'global' ), $this->key ) );
		// And then create your template at located at plugins/<your plugin>/dev/html/latestMoodUpdates.phtml
		
		
		parent::init();
	}
	
	/**
	 * Specify widget configuration
	 *
	 * @param	null|\IPS\Helpers\Form	$form	Form object
	 * @return	null|\IPS\Helpers\Form
	 */
	public function configuration( &$form=null )
	{
 		if ( $form === null )
		{
	 		$form = new \IPS\Helpers\Form;
 		}

		$form->add( new \IPS\Helpers\Form\Number( 'bd_moods_entriesNumber', isset($this->configuration['bd_moods_entriesNumber']) ? $this->configuration['bd_moods_entriesNumber'] : 5,TRUE,array('min'=>1,'max'=>25)) );


		// $$form->add( new \IPS\Helpers\Form\XXXX( .... ) );
 		return $form;
 	} 
 	
 	 /**
 	 * Ran before saving widget configuration
 	 *
 	 * @param	array	$values	Values from form
 	 * @return	array
 	 */
 	public function preConfig( $values )
 	{
 		return $values;
 	}

	/**
	 * Render a widget
	 *
	 * @return	string
	 */
	public function render()
	{
		if (!\IPS\Member::loggedIn()->group['g_bdm_canSee']) {
			return "";
		}

		$updates = array();
		foreach ( \IPS\Db::i()->select('*','bdmoods_updates',NULL,'update_time DESC', (isset($this->configuration['bd_moods_entriesNumber']) ? $this->configuration['bd_moods_entriesNumber'] : 5)) as $row) {
			$mood = \IPS\bdmoods\Mood::load($row['update_mood']);
			if ($mood->mood_id) {
				$member = \IPS\Member::load($row['update_memberid']);
				$updates[]=array('update_member'=>$member,
					'update_time'=>$row['update_time'],
					'update_mood'=>$mood,
					'mood_text'=>$member->moodTitle
				);
			}
		}

		return $this->output($updates);
		// Use $this->output( $foo, $bar ); to return a string generated by the template set in init() or manually added via $widget->template( $callback );
		// Note you MUST route output through $this->output() rather than calling \IPS\Theme::i()->getTemplate() because of the way widgets are cached
	}
}